### ISSUE TITLE
Installation issue (2.0.13)

### ISSUE THREAD

**Issue by vqw** [unbit/uwsgi-docs#309]
Hi guys,

After update to 2.0.13 I was unable to upgrade nor to clean install uwsgi via pip.

**Command**:
Command "/home/users/badInstall/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vybidwwk/uwsgi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-yie6nhtt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-vybidwwk/uwsgi/

**Compiler Error**:
    [thread 2][gcc -pthread] core/signal.o
    [thread 3][gcc -pthread] core/strings.o
    [thread 5][gcc -pthread] core/progress.o
    [thread 4][gcc -pthread] core/timebomb.o
    [thread 6][gcc -pthread] core/ini.o
    [thread 7][gcc -pthread] core/fsmon.o
    [thread 0][gcc -pthread] core/mount.o
    cc1: warnings being treated as errors
    core/lock.c: In function ‘uwsgi_lock_fast_init’:
    **core/lock.c:112: error: implicit declaration of function ‘pthread_mutexattr_setrobust’**
    core/lock.c: In function ‘uwsgi_lock_fast’:
    **core/lock.c:174: error: implicit declaration of function ‘pthread_mutex_consistent’**
    [thread 6][gcc -pthread] core/metrics.o
    [thread 7][gcc -pthread] core/plugins_builder.o

Cheers

**Comment by unbit** [comment]
Unfortunately it looks like 2.0.13 broke older systems. Try latest 2.0 branch patches, they should fix it

**Comment by xrmx** [comment]
@vqw which distribution is this?

**Comment by vqw** [comment]
@xrmx Linux version 3.16.0-70-generic (buildd@lgw01-01) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) 
It's on VPS (that's all I know) from cat /proc/version.

Looks like it's Trusty 14.04 (?)

**Comment by vqw** [comment]
@xrmx Linux version 3.18.25 (gcc version 4.7.2 (Debian 4.7.2-5) )
It's on VPS (that's all I know) from cat /proc/version.

Looks like it's Debian 5 (5.0.10)

**Comment by xrmx** [comment]
This should have been fixed in 2.0.13.1 and debian 5 stopped received security updates 4 years ago...
